#pragma once

//CLASSGEN GENERATED REGION: Includes
//CLASSGEN END REGION
#include <OneStudioPlatform.hpp>
//CLASSGEN GENERATED REGION: Namespace
namespace OneStudio
//CLASSGEN END REGION
//CLASSGEN GENERATED REGION: NamespaceBegin
{
//CLASSGEN END REGION

//CLASSGEN GENERATED REGION: Source
using FileInstance = OSFileSystemItem;
//CLASSGEN END REGION

//CLASSGEN GENERATED REGION: NamespaceEnd
}
//CLASSGEN END REGION
