- Type: Core.AssetManagerSubsystem
  Values:
    Folders:
      - Data
- Type: Input.Subsystem
- Type: Graphics.SFMLRHISubsystem
- Type: Graphics.SFMLSubsystem
- Type: UI2.Subsystem
  Values:
    RootView:
      Type: MainWindowView
- Type: AppFlow.AppFlowSubsystem
  Values:
    Windows:
      MainWindow:
        Scene:
          Type: MainWindowScene
        Title: Editor
        Size:
          X: 1920
          Y: 1080
    StartupWindows:
      - MainWindow
- Type: EditorExtensionSubsystem
- Type: EditorSubsystem
  Values:
    Config:
      Path: Config.yaml
